Repository Gongju-Unity-Bootcamp/HANDSOMEDINO, pull requests merged in 2023-11, with the labels that each got.

#7 Readme Update
  README.md
Labels: question

#6 Readme Update
  README.md
Labels: enhancement

#29 feat: Create prototype map and player. #8
  PPONGARI/Assets/Materials.meta
  PPONGARI/Assets/Materials/PhysicsMaterial.meta
  PPONGARI/Assets/Materials/PhysicsMaterial/protoWall.physicsMaterial2D
  PPONGARI/Assets/Materials/PhysicsMaterial/protoWall.physicsMaterial2D.meta
  PPONGARI/Assets/Materials/ProtoTilemap.meta
  PPONGARI/Assets/Materials/ProtoTilemap/Prototype.prefab
  PPONGARI/Assets/Materials/ProtoTilemap/Prototype.prefab.meta
  PPONGARI/Assets/Materials/ProtoTilemap/protoEnemy.asset
  PPONGARI/Assets/Materials/ProtoTilemap/protoEnemy.asset.meta
  PPONGARI/Assets/Materials/ProtoTilemap/protoEnemy.png
  PPONGARI/Assets/Materials/ProtoTilemap/protoEnemy.png.meta
  PPONGARI/Assets/Materials/ProtoTilemap/protoGround.asset
  PPONGARI/Assets/Materials/ProtoTilemap/protoGround.asset.meta
  PPONGARI/Assets/Materials/ProtoTilemap/protoGround.png
  PPONGARI/Assets/Materials/ProtoTilemap/protoGround.png.meta
  PPONGARI/Assets/Materials/ProtoTilemap/protoWall.asset
  PPONGARI/Assets/Materials/ProtoTilemap/protoWall.asset.meta
  PPONGARI/Assets/Materials/ProtoTilemap/protoWall.png
  PPONGARI/Assets/Materials/ProtoTilemap/protoWall.png.meta
  PPONGARI/Assets/Scenes/MainScene.unity
  PPONGARI/Assets/Scenes/MainScene.unity.meta
  PPONGARI/Assets/Scenes/SampleScene.unity
  PPONGARI/Assets/Scripts.meta
  PPONGARI/ProjectSettings/EditorBuildSettings.asset
  PPONGARI/ProjectSettings/ProjectSettings.asset
  PPONGARI/ProjectSettings/SceneTemplateSettings.json
Labels: enhancement

#31 feat: Create 'playerController.cs' that manage player's movement. #30
  PPONGARI/Assets/Scenes/MainScene.unity
  PPONGARI/Assets/Scripts/playerController.cs
  PPONGARI/Assets/Scripts/playerController.cs.meta
Labels: enhancement

#33 feat : Animation Player idle and walk (#32)
  PPONGARI/Assets/Animation.meta
  PPONGARI/Assets/Animation/Player.controller
  PPONGARI/Assets/Animation/Player.controller.meta
  PPONGARI/Assets/Animation/PlayerIdle.anim
  PPONGARI/Assets/Animation/PlayerIdle.anim.meta
  PPONGARI/Assets/Animation/PlayerWalk.anim
  PPONGARI/Assets/Animation/PlayerWalk.anim.meta
  PPONGARI/Assets/Sprites.meta
  PPONGARI/Assets/Sprites/PlayerIdle.png
  PPONGARI/Assets/Sprites/PlayerIdle.png.meta
  PPONGARI/Assets/Sprites/PlayerWalk.png
  PPONGARI/Assets/Sprites/PlayerWalk.png.meta
Labels: enhancement

#35 feat : MainScene Player Sprite Update (#34)
  PPONGARI/Assets/Scenes/MainScene.unity
Labels: enhancement

#37 feat: Create sprite flip code (#36)
  PPONGARI/Assets/Scripts/playerController.cs
Labels: enhancement

#38 feat: Create Jump system. Modify Input Manager. Add composite Collider 2d (#9)
  PPONGARI/Assets/Scenes/MainScene.unity
  PPONGARI/Assets/Scripts/PlayerMovement.cs
  PPONGARI/Assets/Scripts/PlayerMovement.cs.meta
  PPONGARI/Assets/Scripts/playerController.cs
  PPONGARI/ProjectSettings/InputManager.asset
Labels: bug, enhancement

#43 feat: Create ground judgement system. Limit number of jump times (#15)
  PPONGARI/Assets/Scripts/PlayerMovement.cs
Labels: enhancement

#45 chore: bug fix
  PPONGARI/Assets/Animation/Player.controller
Labels: bug

#47 feat : Player Scripts PlayerAnimation Update (#46)
  PPONGARI/Assets/Animation/Player.controller
  PPONGARI/Assets/Animation/PlayerJump.anim
  PPONGARI/Assets/Animation/PlayerWalk.anim
  PPONGARI/Assets/Animation/Playerdie.anim
  PPONGARI/Assets/Scenes/MainScene.unity
  PPONGARI/Assets/Scripts/PlayerAnimator.cs
  PPONGARI/Assets/Scripts/PlayerAnimator.cs.meta
  PPONGARI/Assets/Scripts/PlayerMovement.cs
  PPONGARI/Assets/Sprites/PlayerJump.png
  PPONGARI/Assets/Sprites/PlayerWalk.png
  PPONGARI/Assets/Sprites/PlayerWalk.png.meta
Labels: enhancement

#48 feat: Create Camera Follow system (#12)
  PPONGARI/Assets/Scenes/MainScene.unity
  PPONGARI/Assets/Scripts/CameraFollow.cs
  PPONGARI/Assets/Scripts/CameraFollow.cs.meta
  PPONGARI/Assets/Scripts/PlayerMovement.cs
  PPONGARI/Assets/Scripts/playerController.cs
Labels: enhancement

#50 feat: Create Player Position Reset Key (#49)
  PPONGARI/Assets/Scripts/CameraFollow.cs
  PPONGARI/Assets/Scripts/PlayerMovement.cs
  PPONGARI/Assets/Scripts/playerController.cs
Labels: enhancement

#52 feat: Wall Jump System (#11)
  PPONGARI/Assets/Scenes/MainScene.unity
  PPONGARI/Assets/Scripts/PlayerMovement.cs
  PPONGARI/Assets/Scripts/playerController.cs
  PPONGARI/ProjectSettings/InputManager.asset
  PPONGARI/ProjectSettings/TagManager.asset
Labels: enhancement

#54 feat: Create Player Respawn System (#53)
  PPONGARI/Assets/Scenes/MainScene.unity
  PPONGARI/Assets/Scripts/PlayerAnimator.cs
  PPONGARI/Assets/Scripts/PlayerRespawn.cs
  PPONGARI/Assets/Scripts/PlayerRespawn.cs.meta
Labels: enhancement

#56 feat : Splash screen Update (#13)
  PPONGARI/Assets/Sprites/LogoBackGraund.png
  PPONGARI/Assets/Sprites/LogoBackGraund.png.meta
  PPONGARI/Assets/Sprites/TeamLogo.png
  PPONGARI/Assets/Sprites/TeamLogo.png.meta
  PPONGARI/ProjectSettings/ProjectSettings.asset
Labels: enhancement

#58 feat: Save & Load System (#55)
  PPONGARI/Assets/Prefabs.meta
  PPONGARI/Assets/Prefabs/CheckPoint1.prefab
  PPONGARI/Assets/Prefabs/CheckPoint1.prefab.meta
  PPONGARI/Assets/Prefabs/Player.prefab
  PPONGARI/Assets/Prefabs/Player.prefab.meta
  PPONGARI/Assets/Scenes/MainScene.unity
  PPONGARI/Assets/Scripts/CheckPoint.cs
  PPONGARI/Assets/Scripts/CheckPoint.cs.meta
  PPONGARI/Assets/Scripts/DeathZone.cs
  PPONGARI/Assets/Scripts/DeathZone.cs.meta
  PPONGARI/Assets/Scripts/PlayerMovement.cs
  PPONGARI/Assets/Scripts/PlayerPosition.cs
  PPONGARI/Assets/Scripts/PlayerPosition.cs.meta
Labels: enhancement

#59 feat : TitleScene update Play and Quit Button (#21-1)
  PPONGARI/Assets/Scenes/TitleScene.unity
  PPONGARI/Assets/Scripts/QuitButton.cs
  PPONGARI/Assets/Scripts/QuitButton.cs.meta
  PPONGARI/Assets/Scripts/StartButton.cs
  PPONGARI/Assets/Scripts/StartButton.cs.meta
  PPONGARI/Assets/Sprites/UI/ButtenSelect.png
  PPONGARI/Assets/Sprites/UI/ButtenSelect.png.meta
  PPONGARI/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement
